version: "2"
services:
  django:
    container_name: django_temperature_sensor
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: django_temperature_sensor
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/django_temperature_sensor
    ports:
      - "8083:8083"
      - "13306:3306"
    networks:
      net1:
        ipv4_address: 172.19.0.2


networks:
  net1:
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/24


