version: "2"
services:
  django:
    container_name: django_temperature_sensor2
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: django_temperature_sensor2
    stdin_open: true
    tty: true
    volumes:
      - ./database/:/var/www/django/temperature_sensor/database/
    ports:
      - "8083:8083"
