version: "2"
services:
  django:
    container_name: django_temperature_sensor2
    build:
      context: .
      dockerfile: Dockerfile
    image: django_temperature_sensor2
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/django_temperature_sensor
    ports:
      - "8083:8083"
    networks:
      net1:
        ipv4_address: 172.19.0.2


networks:
  net1:
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/24


